name: Upgrade nightly version
on:
  schedule:
    - cron: 5 0 * * *  # At 12:05 AM
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pixi-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.2
          cache: true

      - name: Run upgrade
        run: pixi run upgrade

      - name: Lint
        run: pixi run lint_docs

      - name: Test
        run: pixi run tests

      - name: Get the version
        id: get_version
        run: |
          TAG="$(pixi project version get)-compiler-$(pixi list | grep 'mojo-compiler' | awk '{print $2}')"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin refs/tags/${{ steps.get_version.outputs.TAG }} | grep -q "${{ steps.get_version.outputs.TAG }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push
        if: steps.check_tag.outputs.exists != 'true'
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update lockfile to latest Mojo version"
          branch: main

      - name: Upload package to release
        if: steps.check_tag.outputs.exists != 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./build/mojo_datetime.mojopkg
          tag: ${{ steps.get_version.outputs.TAG }}
          overwrite: false